### ISSUE TITLE
label problem

### ISSUE THREAD

**Issue by benjamc** [automl/CARP-S#86]
```yaml
problem_characteristics:
   n_objectives: int
   objectives: list[str]
   dimensions: int
   multifidelity: bool
   fidelity_type: null/compute/dataset
   constraints: bool
   domain: synthetic, ML, NAS, x
   objective_function_approximation: [surrogate, tabular, real]
   search_space:
       has_conditionals: bool
       has_constraints: bool
       has_priors: bool
```
